/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthSignOutRouteImport } from './routes/auth/sign-out'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppDemoPublicDataRouteImport } from './routes/app/demo/public-data'
import { Route as AppDemoPrivateNotesRouteImport } from './routes/app/demo/private-notes'
import { Route as AppDemoAuditLogRouteImport } from './routes/app/demo/audit-log'
import { Route as AppDemoApiAccessRouteImport } from './routes/app/demo/api-access'
import { Route as AppDemoAdminPanelRouteImport } from './routes/app/demo/admin-panel'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/auth/sign-out',
  path: '/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDemoPublicDataRoute = AppDemoPublicDataRouteImport.update({
  id: '/demo/public-data',
  path: '/demo/public-data',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDemoPrivateNotesRoute = AppDemoPrivateNotesRouteImport.update({
  id: '/demo/private-notes',
  path: '/demo/private-notes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDemoAuditLogRoute = AppDemoAuditLogRouteImport.update({
  id: '/demo/audit-log',
  path: '/demo/audit-log',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDemoApiAccessRoute = AppDemoApiAccessRouteImport.update({
  id: '/demo/api-access',
  path: '/demo/api-access',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDemoAdminPanelRoute = AppDemoAdminPanelRouteImport.update({
  id: '/demo/admin-panel',
  path: '/demo/admin-panel',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/app/': typeof AppIndexRoute
  '/app/demo/admin-panel': typeof AppDemoAdminPanelRoute
  '/app/demo/api-access': typeof AppDemoApiAccessRoute
  '/app/demo/audit-log': typeof AppDemoAuditLogRoute
  '/app/demo/private-notes': typeof AppDemoPrivateNotesRoute
  '/app/demo/public-data': typeof AppDemoPublicDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/app': typeof AppIndexRoute
  '/app/demo/admin-panel': typeof AppDemoAdminPanelRoute
  '/app/demo/api-access': typeof AppDemoApiAccessRoute
  '/app/demo/audit-log': typeof AppDemoAuditLogRoute
  '/app/demo/private-notes': typeof AppDemoPrivateNotesRoute
  '/app/demo/public-data': typeof AppDemoPublicDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/app/': typeof AppIndexRoute
  '/app/demo/admin-panel': typeof AppDemoAdminPanelRoute
  '/app/demo/api-access': typeof AppDemoApiAccessRoute
  '/app/demo/audit-log': typeof AppDemoAuditLogRoute
  '/app/demo/private-notes': typeof AppDemoPrivateNotesRoute
  '/app/demo/public-data': typeof AppDemoPublicDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/app/'
    | '/app/demo/admin-panel'
    | '/app/demo/api-access'
    | '/app/demo/audit-log'
    | '/app/demo/private-notes'
    | '/app/demo/public-data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/app'
    | '/app/demo/admin-panel'
    | '/app/demo/api-access'
    | '/app/demo/audit-log'
    | '/app/demo/private-notes'
    | '/app/demo/public-data'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/app/'
    | '/app/demo/admin-panel'
    | '/app/demo/api-access'
    | '/app/demo/audit-log'
    | '/app/demo/private-notes'
    | '/app/demo/public-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/sign-out': {
      id: '/auth/sign-out'
      path: '/auth/sign-out'
      fullPath: '/auth/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/demo/public-data': {
      id: '/app/demo/public-data'
      path: '/demo/public-data'
      fullPath: '/app/demo/public-data'
      preLoaderRoute: typeof AppDemoPublicDataRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/demo/private-notes': {
      id: '/app/demo/private-notes'
      path: '/demo/private-notes'
      fullPath: '/app/demo/private-notes'
      preLoaderRoute: typeof AppDemoPrivateNotesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/demo/audit-log': {
      id: '/app/demo/audit-log'
      path: '/demo/audit-log'
      fullPath: '/app/demo/audit-log'
      preLoaderRoute: typeof AppDemoAuditLogRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/demo/api-access': {
      id: '/app/demo/api-access'
      path: '/demo/api-access'
      fullPath: '/app/demo/api-access'
      preLoaderRoute: typeof AppDemoApiAccessRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/demo/admin-panel': {
      id: '/app/demo/admin-panel'
      path: '/demo/admin-panel'
      fullPath: '/app/demo/admin-panel'
      preLoaderRoute: typeof AppDemoAdminPanelRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDemoAdminPanelRoute: typeof AppDemoAdminPanelRoute
  AppDemoApiAccessRoute: typeof AppDemoApiAccessRoute
  AppDemoAuditLogRoute: typeof AppDemoAuditLogRoute
  AppDemoPrivateNotesRoute: typeof AppDemoPrivateNotesRoute
  AppDemoPublicDataRoute: typeof AppDemoPublicDataRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDemoAdminPanelRoute: AppDemoAdminPanelRoute,
  AppDemoApiAccessRoute: AppDemoApiAccessRoute,
  AppDemoAuditLogRoute: AppDemoAuditLogRoute,
  AppDemoPrivateNotesRoute: AppDemoPrivateNotesRoute,
  AppDemoPublicDataRoute: AppDemoPublicDataRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
